

artists_genres = {
                  "metallica" : "metal",
                  "meshuggah" : "metal",
                  "immortal" : "metal",
                  "megadeth" : "metal",
                  "necrophagist" : "metal",
                  "cannibal_corpse" : "metal",
                  "iron_maiden" : "metal",
                  "black_sabbath" : "metal",
                  "slipknot" : "metal",
                  "judas_priest" : "metal",
                  "pantera" : "metal",
                  "slayer" : "metal",
                  "lamb_of_god" : "metal",
                  "motorhead" : "metal",
                  "dream_theater" : "metal",
                  "manowar" : "metal",
                  "mercyful_fate" : "metal",
                  "death" : "metal",
                  "children_of_bodom" : "metal",
                  "dark_funeral" : "metal",
                   "system_of_a_down" : "metal",
                    "opeth": "metal",
                    "blind_guardian": "metal",
                    "mastodon": "metal",
                    "arch_enemy": "metal",
                    "dimmu_borgir": "metal",
                    "dio": "metal",
                    "marduk": "metal",
                    "type_o_negative": "metal",
                    "pain": "metal",

                  "katy_perry" : "pop",
                  "miley_cyrus" : "pop",
                  "ed_sheeran" : "pop",
                  "bruno_mars" : "pop",
                  "taylor_swift" : "pop",
                  "madonna" : "pop",
                  "britney_spears" : "pop",
                  "rihanna" : "pop",
                  "michael_jackson" : "pop",
                  "lady_gaga" : "pop",
                  "the_beatles" : "pop",
                  "justin_bieber" : "pop",
                  "justin_timberlake" : "pop",
                  "mariah_carey" : "pop",
                  "selena_gomez" : "pop",
                  "elton_john" : "pop",
                  "prince" : "pop",
                  "ariana_grande" : "pop",
                  "shakira" : "pop",
                  "cher" : "pop",
"avril_lavigne" : "pop",
"christina_aguilera" : "pop",
"nelly_furtado" : "pop",
"abba" : "pop",
"beyonce_knowles" : "pop",
"gwen_stefani" : "pop",
"mika" : "pop",
"jennifer_lopez" : "pop",
"kesha" : "pop",
"lana_del_rey" : "pop",

                  "eazy_e" : "rap",
                  "2pac" : "rap",
                  "drake" : "rap",
                  "snoop_dogg" : "rap",
                  "dr__dre" : "rap",
                  "post_malone" : "rap",
                  "eminem" : "rap",
                  "kanye_west" : "rap",
                  "kendrick_lamar" : "rap",
                  "ice_cube" : "rap",
                  "50_cent" : "rap",
                  "lil_wayne" : "rap",
                  "notorious_b_i_g_" : "rap",
                  "dmx" : "rap",
                  "jay_z" : "rap",
                  "wu_tang_clan" : "rap",
                  "p__diddy" : "rap",
                  "travis_scott_" : "rap",
                  "mac_miller" : "rap",
                  "g_eazy" : "rap",
    "busta_rhymes": "rap",
    "the_game": "rap",
    "nwa": "rap",
    "xzibit": "rap",
    "die_antwoord": "rap",
    "coolio": "rap",
    "chris_brown": "rap",
    "rae_sremmurd": "rap",
    "t_pain": "rap",
    "soulja_boy": "rap",
                  }